version: 2

sources:
  - name: maquina1_staging
    schema: public      
    database: dw          

    tables:
      - name: circuits
      - name: constructors
      - name: drivers
      - name: seasons
      - name: status
      - name: races
      - name: results
      - name: driver_standings
      - name: constructor_results
      - name: qualifying
      - name: laptimes
      - name: pitstops

